
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8.0
  application:
    name: user-service

mybatis-plus:
  type-aliases-package: com.zbbmeta.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/

