server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elastic?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zbbmeta: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zbbmeta.elastic.entity