server:
  port: 9999 # 网关端口
spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    # 开启nacos负载均衡策略
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      routes: # 网关路由配置
      - id: user-service # 路由id，自定义，只要唯一即可
        #uri: http://127.0.0.1:8088 # 路由的目标地址 http就是固定地址
        uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
        predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
          - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        filters:
          - AddRequestHeader=Learn, learn springbot! # 添加请求头
      default-filters: # 默认过滤项
        - AddRequestHeader=Learn, learn springbot! # 添加请求头
