server:
  port: 9099

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #    loadbalancer:
  #      nacos:
  #        enabled: true #表示启用了 NacosLoadBalancer
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8.0


mybatis-plus:
  type-aliases-package: com.zbbmeta.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_

feign:
  client:
    config:
      user-service: # 针对某个微服务的配置
        loggerLevel: FULL #  日志级别

  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数