server:
  port: 9999

spring:
  rabbitmq:
    host: 192.168.150.102 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: zbbmeta # 用户名
    password: 123456 # 密码
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto # 模式类似事务机制，出现异常时返回nack，消息回滚到mq；没有异常，返回ack
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000 # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false

  application:
    name:  mq-consumer