server:
  port: 8888

spring:
  rabbitmq:
    host: 192.168.150.102 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: zbbmeta # 用户名
    password: 123456 # 密码
    publisher-confirm-type: correlated # 异步回调
    publisher-returns: true
    template:
      mandatory: false


  application:
    name: mq-publisher

