server:
  port: 8888

spring:
  rabbitmq:
    host: 192.168.150.102 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: zbbmeta # 用户名
    password: 123456 # 密码
  application:
    name: mq-publisher

