spring:
  boot:
    admin:
      client:
        url: http://localhost:8080

server:
  port: 9999

management:
  endpoint: # 具体端点的配置
    health:
      show-details: always
    info:
      enabled: true
      appName: @project.artifactId@
      version: @project.version@
      company: springboot葵花宝典
      author: zbbmeta
  endpoints: # 全部端点的配置
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  info: #配置info信息 2.5以上需要配置，不然下面的info信息不生效
    env:
      enabled: true
info:
  appName: @project.artifactId@
  version: @project.version@
  company: springboot葵花宝典
  author: zbbmeta