server:
  port: 9999


spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
    register-with-eureka: false
    fetch-registry: false
