server:
  port: 8088
spring:
  application:
    name: task-demo


xxl:
  job:
    adminAddresses: "http://localhost:8080/xxl-job-admin"
    accessToken:
    appname: "test-executor"
    address:
    ip:
    port: 9999
    logpath: "/data/applogs/xxl-job/jobhandler"
    logretentiondays: 30